POST http://localhost:3000/auth/sign-up
content-type: application/json

{
  "username":"username",
  "password":"pass",
  "passwordConfirm":"pass"
}
###
POST http://localhost:3000/auth/sign-in
content-type: application/json

{
  "username":"username",
  "password":"pass"
}